int pinnum2 = 2;
int pinnum3 = 3;
int pinnum4 = 4;
int pinnum5 = 5;
int pinnum6 = 6;
int pinnum7 = 7;
int pinnum8 = 8;
int pinnum10 = 10;
int blinkdel = 50;
void oldjump(){
  digitalWrite(pinnum2, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum2, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum2, LOW);
  delay(blinkdel);
  digitalWrite(pinnum2, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum2, LOW);
  delay(blinkdel);
}
void cyclesmooth(){
  digitalWrite(pinnum2, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum2, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum10, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum10, LOW);
  delay(blinkdel);
  digitalWrite(pinnum8, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum8, LOW);
  delay(blinkdel);
  digitalWrite(pinnum7, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum7, LOW);
  delay(blinkdel);
  digitalWrite(pinnum6, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum6, LOW);
  delay(blinkdel);
  digitalWrite(pinnum5, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum5, LOW);
  delay(blinkdel);
  digitalWrite(pinnum4, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum4, LOW);
  delay(blinkdel);
  digitalWrite(pinnum3, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum3, LOW);
  delay(blinkdel);
  digitalWrite(pinnum2, HIGH);
  delay(blinkdel);
  digitalWrite(pinnum2, LOW);
  delay(blinkdel);
}
void setup() {
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(10, OUTPUT);
}

void loop() {
  cyclesmooth();
  
  
  }
